# Generated by Django 5.1.6 on 2025-04-03 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_stream_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myapp.stream'),
        ),
    ]
