# Generated by Django 5.1.6 on 2025-04-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_order_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='competition_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin/'),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='finish',
            field=models.DateField(default='2025-03-20'),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='start',
            field=models.DateField(default='2024-09-20'),
        ),
    ]
