# Generated by Django 5.1.6 on 2025-04-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_adminsetting_competition_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
