# Generated by Django 5.1.6 on 2025-04-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_thread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_at']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='thread',
            new_name='stream',
        ),
    ]
