# Generated by Django 5.1.6 on 2025-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_order_stream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminsetting',
            options={'verbose_name': 'Admin Setting', 'verbose_name_plural': 'Admin Settings'},
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='competition_photo',
            field=models.ImageField(blank=True, help_text='Upload an image related to the competition.', null=True, upload_to='admin/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='deliver_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Delivery price in whole numbers.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='description',
            field=models.TextField(blank=True, help_text='Optional competition details.', null=True),
        ),
    ]
