# Generated by Django 5.1.6 on 2025-04-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_operator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.district'),
        ),
        migrations.AddField(
            model_name='order',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
